// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { ChainLinkConfig, ChainLinkConfigData, ChainLinkConfigTableId } from "./tables/ChainLinkConfig.sol";
import { ChainLinkRequest, ChainLinkRequestData, ChainLinkRequestTableId } from "./tables/ChainLinkRequest.sol";
import { TxHashToChainLinkRequest, TxHashToChainLinkRequestTableId } from "./tables/TxHashToChainLinkRequest.sol";
import { AweiTokenMetadata, AweiTokenMetadataData } from "./tables/AweiTokenMetadata.sol";
import { AweiToken, AweiTokenData } from "./tables/AweiToken.sol";
import { AweiTokenBalance } from "./tables/AweiTokenBalance.sol";
import { AweiTokenApproval } from "./tables/AweiTokenApproval.sol";
