// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { IAxiom } from "./../../axiom.sol";

/**
 * @title IAxiomSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAxiomSystem {
  function claim(bytes calldata txPayload, uint8 v, IAxiom.Proof calldata proof, uint256 tokenId) external;
}
