// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IConfigSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IConfigSystem {
  function setSource(string memory _source) external;

  function setSubscriptionId(uint64 _subscriptionId) external;

  function setCallbackGasLimit(uint32 _callbackGasLimit) external;
}
