// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITokenSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITokenSystem {
  function mint() external payable;
}
