// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { VoteType } from "./../common.sol";

/**
 * @title IVoteSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IVoteSystem {
  function computeVotingPower(uint256[] calldata _tokenIds) external view returns (uint256);

  function voteTo(address game, VoteType voteType) external;
}
